name: TruffleHog Scan Test

on:
  push:
    branches:
      - '**'
  pull_request:

permissions:
  contents: read

jobs:
  trufflehog:
    name: TruffleHog scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog scan
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          base: ${{ github.event.before }}
          head: HEAD
          extra_args: --debug --only-verified --json --output=trufflehog-results.json

      - name: Display TruffleHog results
        if: always()
        shell: bash
        run: |
          if [ -f trufflehog-results.json ]; then
            cat trufflehog-results.json
          else
            echo "Nenhum arquivo de resultado foi gerado."
          fi

      - name: Upload TruffleHog results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-results.json
          if-no-files-found: warn
