name: TruffleHog Scan Test

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog scan
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          base: ${{ github.event.before }}
          head: HEAD
          extra_args: --debug --only-verified --json --output=trufflehog-results.json

      - name: Display TruffleHog results
        if: always()
        run: |
          if [ -f trufflehog-results.json ]; then
            cat trufflehog-results.json
          else
            echo "Nenhum resultado foi gerado."
          fi

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-results.json
